name: Michele Pierangeli
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25889
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00b882'
    - '#00c084'
    - '#00ca8a'
    - '#00cf8d'
    - '#00b07d'
  brandStrength: 0.5
  lightness: 0.8626432423479855
  saturation: 0.2963966589886695
  rhythmicContrast: 0.8194884173572063
purpose: []
